# Generated by Django 6.1.1 on 2026-09-11 14:59

import django.db.models.deletion
import orders.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, default='', max_length=9)),
                ('vehicle', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('CAR', 'Car'), ('VAN', 'Van')], max_length=16)),
                ('plate', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'In transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_TRANSIT', max_length=16)),
                ('stage', models.CharField(choices=[('REQUEST_CREATED', 'Request created'), ('DRIVER_ASSIGNED', 'Driver assigned'), ('DRIVER_ARRIVING', 'Driver arriving'), ('PICKED_UP', 'Picked up'), ('DELIVERED', 'Delivered')], default='REQUEST_CREATED', max_length=24)),
                ('vehicle', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('CAR', 'Car'), ('VAN', 'Van')], max_length=16)),
                ('price_tsh', models.PositiveIntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('PAY_AFTER_DELIVERY', 'Pay after delivery')], default='PAY_AFTER_DELIVERY', max_length=24)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_landmark', models.CharField(blank=True, default='', max_length=255)),
                ('pickup_instructions', models.CharField(blank=True, default='', max_length=500)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_address', models.CharField(max_length=255)),
                ('dropoff_landmark', models.CharField(blank=True, default='', max_length=255)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('delivery_instructions', models.CharField(blank=True, default='', max_length=500)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=9)),
                ('package_type', models.CharField(choices=[('DOCUMENTS', 'Documents'), ('CLOTHES', 'Clothes'), ('FOOD', 'Food'), ('ELECTRONICS', 'Electronics'), ('HOUSEHOLD', 'Household item'), ('OTHER', 'Other')], max_length=16)),
                ('package_size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=16)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('package_description', models.CharField(blank=True, default='', max_length=500)),
                ('handling_instructions', models.CharField(blank=True, default='', max_length=500)),
                ('package_photo', models.ImageField(blank=True, null=True, upload_to=orders.models._package_photo_path)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('my_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.driver')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='orders_custome_58f6c3_idx'), models.Index(fields=['order_number'], name='orders_order_n_1336be_idx')],
            },
        ),
    ]
