# Generated by Django 6.1.1 on 2026-09-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('BAJAJI', 'Bajaji'), ('CAR', 'Car'), ('VAN', 'Lorry')], max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle',
            field=models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('BAJAJI', 'Bajaji'), ('CAR', 'Car'), ('VAN', 'Lorry')], max_length=16),
        ),
    ]
