import 'package:jihudumie_app/orders/order_models.dart';

/// Fixture data for tests and goldens only -- production code fetches real
/// orders from the backend now (`JhOrdersApi`/`JhAppState.loadOrders`). Kept
/// here rather than in `lib/` because nothing outside a test imports it.
List<JhOrder> buildSampleOrders() => [
  JhOrder(
    id: 'JHD-20260910-00125',
    serverId: 'srv-00125',
    pickupArea: 'Makongo',
    dropoffArea: 'Goba',
    status: JhOrderStatus.inTransit,
    stage: JhTrackingStage.pickedUp,
    vehicle: JhVehicle.motorcycle,
    priceTsh: 5000,
    paid: false,
    paymentMethod: JhPaymentMethod.payAfterDelivery,
    createdAt: DateTime(2026, 9, 10, 8, 30),
    recipientName: 'Juma Ally',
    recipientPhone: '712345678',
    packageType: JhPackageType.documents,
    packageSize: JhPackageSize.small,
    quantity: 1,
    pickupAddress: 'Makongo Juu, Dar es Salaam',
    pickupLandmark: 'Near the market',
    pickupInstructions: 'Call on arrival',
    pickupLat: -6.7660,
    pickupLng: 39.2220,
    dropoffAddress: 'Goba, Dar es Salaam',
    dropoffLandmark: 'Near ABC Petrol Station',
    dropoffLat: -6.7000,
    dropoffLng: 39.1950,
    deliveryInstructions: 'Leave with the receptionist',
    packageDescription: 'Sealed envelope of documents',
    handlingInstructions: '',
    driver: const JhDriver(
      name: 'John Michael',
      rating: 4.8,
      vehicle: JhVehicle.motorcycle,
      plate: 'T 123 ABC',
    ),
  ),
  JhOrder(
    id: 'JHD-20260909-00121',
    serverId: 'srv-00121',
    pickupArea: 'Mikocheni',
    dropoffArea: 'Kimara',
    status: JhOrderStatus.inTransit,
    stage: JhTrackingStage.driverArriving,
    vehicle: JhVehicle.motorcycle,
    priceTsh: 6000,
    paid: true,
    paymentMethod: JhPaymentMethod.payAfterDelivery,
    createdAt: DateTime(2026, 9, 9, 16, 5),
    recipientName: 'Neema Said',
    recipientPhone: '763221100',
    packageType: JhPackageType.clothes,
    packageSize: JhPackageSize.medium,
    quantity: 2,
    pickupAddress: 'Mikocheni B, Dar es Salaam',
    pickupLandmark: 'Opposite the pharmacy',
    pickupInstructions: '',
    pickupLat: -6.7720,
    pickupLng: 39.2630,
    dropoffAddress: 'Kimara, Dar es Salaam',
    dropoffLandmark: '',
    dropoffLat: -6.7880,
    dropoffLng: 39.1640,
    deliveryInstructions: '',
    packageDescription: 'Two folded garments',
    handlingInstructions: 'Keep dry',
    driver: const JhDriver(
      name: 'Grace Mushi',
      rating: 4.9,
      vehicle: JhVehicle.motorcycle,
      plate: 'T 456 DEF',
    ),
  ),
  JhOrder(
    id: 'JHD-20260905-00098',
    serverId: 'srv-00098',
    pickupArea: 'Sinza',
    dropoffArea: 'Mikocheni',
    status: JhOrderStatus.completed,
    stage: JhTrackingStage.delivered,
    vehicle: JhVehicle.motorcycle,
    priceTsh: 6000,
    paid: true,
    paymentMethod: JhPaymentMethod.payAfterDelivery,
    createdAt: DateTime(2026, 9, 5, 14, 10),
    recipientName: 'Baraka John',
    recipientPhone: '715908070',
    packageType: JhPackageType.food,
    packageSize: JhPackageSize.small,
    quantity: 1,
    pickupAddress: 'Sinza Mori, Dar es Salaam',
    pickupLandmark: '',
    pickupInstructions: '',
    pickupLat: -6.7820,
    pickupLng: 39.2230,
    dropoffAddress: 'Mikocheni, Dar es Salaam',
    dropoffLandmark: '',
    dropoffLat: -6.7720,
    dropoffLng: 39.2630,
    deliveryInstructions: '',
    packageDescription: 'Lunch delivery',
    handlingInstructions: 'Handle upright',
    driver: const JhDriver(
      name: 'Peter Mwakalinga',
      rating: 4.7,
      vehicle: JhVehicle.motorcycle,
      plate: 'T 789 GHI',
    ),
  ),
  JhOrder(
    id: 'JHD-20260901-00074',
    serverId: 'srv-00074',
    pickupArea: 'Kinondoni',
    dropoffArea: 'Kawe',
    status: JhOrderStatus.completed,
    stage: JhTrackingStage.delivered,
    vehicle: JhVehicle.car,
    priceTsh: 9000,
    paid: true,
    paymentMethod: JhPaymentMethod.payAfterDelivery,
    createdAt: DateTime(2026, 9, 1, 9, 45),
    recipientName: 'Amina Hassan',
    recipientPhone: '712345678',
    packageType: JhPackageType.electronics,
    packageSize: JhPackageSize.medium,
    quantity: 1,
    pickupAddress: 'Kinondoni, Dar es Salaam',
    pickupLandmark: '',
    pickupInstructions: '',
    pickupLat: -6.7920,
    pickupLng: 39.2580,
    dropoffAddress: 'Kawe, Dar es Salaam',
    dropoffLandmark: '',
    dropoffLat: -6.7120,
    dropoffLng: 39.2260,
    deliveryInstructions: 'Signature required',
    packageDescription: 'Laptop in a padded bag',
    handlingInstructions: 'Fragile',
    driver: const JhDriver(
      name: 'Salum Kondo',
      rating: 4.9,
      vehicle: JhVehicle.car,
      plate: 'T 210 JKL',
    ),
  ),
  JhOrder(
    id: 'JHD-20260828-00051',
    serverId: 'srv-00051',
    pickupArea: 'Tabata',
    dropoffArea: 'Ukonga',
    status: JhOrderStatus.cancelled,
    stage: JhTrackingStage.requestCreated,
    vehicle: JhVehicle.motorcycle,
    priceTsh: 4500,
    paid: false,
    paymentMethod: JhPaymentMethod.payAfterDelivery,
    createdAt: DateTime(2026, 8, 28, 11, 20),
    recipientName: 'Salma Omary',
    recipientPhone: '764110099',
    packageType: JhPackageType.other,
    packageSize: JhPackageSize.small,
    quantity: 1,
    pickupAddress: 'Tabata Kimanga, Dar es Salaam',
    pickupLandmark: '',
    pickupInstructions: '',
    pickupLat: -6.8470,
    pickupLng: 39.2350,
    dropoffAddress: 'Ukonga, Dar es Salaam',
    dropoffLandmark: '',
    dropoffLat: -6.8500,
    dropoffLng: 39.2860,
    deliveryInstructions: '',
    packageDescription: '',
    handlingInstructions: '',
  ),
];
